### ISSUE TITLE
Not able compile the current project.

### ISSUE THREAD

**Issue by szmulder** [weltkante/managed-lzma#2]
The line 
"writer.InitializeLzma2Encoder();" not able compiled.

I change it to 
"writer.ConnectEncoder(new ArchiveWriter.Lzma2Encoder(1, null));"
then works fine.

**Comment by weltkante** [comment]
Right thanks, that's in one of the sample/test projects, not in the actual library, will be fixed.

**Comment by weltkante** [comment]
With the fix the sample compiles but doesn't terminate anymore (at least for me), there are 3 hanging threads waiting for further instructions, I've opened issue #4 for that because I'm not sure if thats a bug or if the fix was just wrong; in particular the fix for this issue doesn't dispose the Lzma2Encoder.
